spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
#配置全局配置文件
##配置mapper映射文件
mybatis:
  config-location: classpath:Mybatis/mybatis_config.xml
  mapper-locations: classpath:Mybatis/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
